### ISSUE TITLE
Twitch Indicator is perpetually "Checking" 

### ISSUE THREAD

**Issue by JEBTech** [rbrs/ubuntu-twitch-indicator#10]
My Twitch indicator is perpetually "Checking". It stopped listing live channels about a week ago. Is there an update or fix?  

Ubuntu 16.04

**Comment by Nezchan** [comment]
Same issue, except it started late in the day on September 14. I suspect it's linked to Twitch's switch to requiring tokens.

**Comment by rolandasb** [comment]
Thanks, should be fine now.
