### ISSUE TITLE
Lower GTK requirement (latest Twitch Indicator requires GTK 3.12)

### ISSUE THREAD

**Issue by hotice** [rbrs/ubuntu-twitch-indicator#2]
The latest Twitch Indicator requires GTK 3.12:

```
Traceback (most recent call last):
  File "/usr/bin/twitch-indicator", line 154, in settings_dialog
    self.builder.add_from_file("/usr/lib/twitch-indicator/twitch-indicator.glade")
gi._glib.GError: /usr/lib/twitch-indicator/twitch-indicator.glade: required gtk+ version 3.12, current version is 3.10
```

This means it no longer works on Ubuntu 14.04 (the initial version worked)... can this be tweaked to work with at least GTK 3.10?

**Comment by rolandasb** [comment]
Thanks for the report. I tested on 14.04 (with gtk 3.10) and everything now seems to work. Let me know if there are any issues.

**Comment by hotice** [comment]
Thank you!
