### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by ejkarne** [rbrs/ubuntu-twitch-indicator#7]
For a while now it's just thrown this error during every update

> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 754, in run
>     self.__target(_self.__args, *_self.__kwargs)
>   File "/usr/bin/twitch-indicator", line 236, in refresh_streams
>     self.live_streams = self.tw.fetch_live_streams(self.followed_channels)
>   File "/usr/bin/twitch-indicator", line 57, in fetch_live_streams
>     self.f = urllib.urlopen("https://api.twitch.tv/kraken/streams?channel={0}".format(','.join(self.channels_offset)))
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 176: ordinal not in range(128)

**Comment by ejkarne** [comment]
Seems to be an issue when following a channel with special characters (in my case é). The website seems to convert these characters everywhere however, the api 

> https://api.twitch.tv/kraken/users/greyasteroid/follows/channels?direction=DESC&limit=100&offset={1}&sortby=created_at

for example, returns these special characters.

**Comment by rolandasb** [comment]
This should be fixed with #14, please reopen this issue if you're still having problems. Thanks :)
